version: "1"
services:
  - type: web
    name: swarm-intelligence
    env: static
    buildCommand: "npm run build"
    staticPublishPath: "dist"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"